import { VOS_FULL_PARAMETERS, VOS_TERMINOLOGY } from "./vos-online-config";

export const LOCAL_VOS_NETWORK = {
  network: {
    items: [
      {
        id: 1,
        label: "圣保禄学院",
        x: -0.62,
        y: -0.18,
        cluster: 1,
        weights: { Documents: 48, Citations: 620 },
        scores: { "Avg. pub. year": 2008.4, "Avg. citations": 12.9 },
      },
      {
        id: 2,
        label: "天主之母教堂前壁",
        x: -0.34,
        y: 0.42,
        cluster: 1,
        weights: { Documents: 36, Citations: 410 },
        scores: { "Avg. pub. year": 2011.2, "Avg. citations": 11.4 },
      },
      {
        id: 3,
        label: "大炮台",
        x: 0.12,
        y: 0.58,
        cluster: 2,
        weights: { Documents: 29, Citations: 280 },
        scores: { "Avg. pub. year": 2014.6, "Avg. citations": 9.7 },
      },
      {
        id: 4,
        label: "议事亭前地",
        x: 0.55,
        y: 0.08,
        cluster: 2,
        weights: { Documents: 41, Citations: 355 },
        scores: { "Avg. pub. year": 2016.1, "Avg. citations": 8.7 },
      },
      {
        id: 5,
        label: "妈阁庙",
        x: 0.48,
        y: -0.52,
        cluster: 3,
        weights: { Documents: 33, Citations: 190 },
        scores: { "Avg. pub. year": 2018.3, "Avg. citations": 5.8 },
      },
      {
        id: 6,
        label: "东望洋炮台",
        x: -0.08,
        y: -0.61,
        cluster: 3,
        weights: { Documents: 22, Citations: 150 },
        scores: { "Avg. pub. year": 2019.5, "Avg. citations": 6.8 },
      },
      {
        id: 7,
        label: "澳门历史城区",
        x: 0.02,
        y: 0.02,
        cluster: 1,
        weights: { Documents: 90, Citations: 980 },
        scores: { "Avg. pub. year": 2013.8, "Avg. citations": 10.9 },
      },
    ],
    links: [
      { source_id: 1, target_id: 2, strength: 24 },
      { source_id: 1, target_id: 3, strength: 11 },
      { source_id: 1, target_id: 7, strength: 40 },
      { source_id: 2, target_id: 7, strength: 32 },
      { source_id: 3, target_id: 7, strength: 18 },
      { source_id: 4, target_id: 7, strength: 21 },
      { source_id: 4, target_id: 5, strength: 8 },
      { source_id: 5, target_id: 7, strength: 14 },
      { source_id: 6, target_id: 7, strength: 12 },
      { source_id: 3, target_id: 6, strength: 6 },
    ],
  },
  config: {
    parameters: {
      ...VOS_FULL_PARAMETERS,
      scale: 1.1,
    },
    terminology: VOS_TERMINOLOGY.zh,
  },
  info: {
    title: "本机示例网络",
    description: "数据在 Studio 内存里，没有上传到 app.vosviewer.com。",
  },
};
